FROM quay.io/biocontainers/bcftools:1.21--h8b25389_0

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends samtools ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# bcftools plugins already in /usr/local/libexec/bcftools in this base image
ENV BCFTOOLS_PLUGINS=/usr/local/libexec/bcftools

# your helper scripts
COPY scripts/harmonize_vcf_bam.sh /usr/local/bin/harmonize_vcf_bam.sh
RUN chmod +x /usr/local/bin/harmonize_vcf_bam.sh

WORKDIR /work
